---
title: "Добро пожаловать в блог (Ре)анализ данных из любопытства"
description: |
  Мы создали блог (Ре)анализ данных из любопытства, чтобы учиться применять разные методы анализа к реальным данным.
author:
  - name: Марина Варфоломеева
  - name: Ирина Бабкина
  - name: Лаврентий Данилов
  - name: Вадим Хайтов 
date: 12-27-2018
categories:
  - Структура блога
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Radix at:
# https://rstudio.github.io/radix/blog.html

```

Искусство анализа данных сложно постичь, решая тщательно подобранные примеры в Университетских курсах статистики. Мы создали блог "(Ре)анализ данных из любопытства", чтобы учиться применять разные методы анализа к реальным данным.

В этом посте --- наш первоначальный план действий. Текущая версия будет [на странице о блоге](../../about.html).

## Цели:

- Анализируем данные в "боевых" условиях. 
- Развиваем понимание знакомых методов, чтобы отойти от рецептов.
- Изучаем новые методы анализа.

## Формат:

- Находим интересные данные.
- Делаем разведочный анализ.
- Пытаемся воспроизвести анализ авторов данных настолько, насколько это возможно по описанию. Находим ограничения и сильные стороны.
- Предлагаем свои альтернативные методы решения. (Или решаем совсем другие вопросы, используя эти данные для отработки новых для нас методов).
- Собираемся вместе и обсуждаем, что получилось.
- По итогам обсуждения пишем пост в блог.
- Стараемся повторять все это регулярно...

## Структура проекта:

Общий репозиторий. У каждого своя именная ветка. В ветке master лежит этот блог с чистовыми постами.


Обсуждаемо.
